/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedScorecardRouteImport } from './routes/_authenticated/scorecard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ProcessIdRouteImport } from './routes/process.$id'
import { Route as ScheduleTokenRouteImport } from './routes/schedule.$token'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'
import { Route as AuthenticatedCandidatesNewRouteImport } from './routes/_authenticated/candidates.new'
import { Route as AuthenticatedEvaluationsIndexRouteImport } from './routes/_authenticated/evaluations.index'
import { Route as AuthenticatedEvaluationsApplicationIdRouteImport } from './routes/_authenticated/evaluations.$applicationId'
import { Route as ApiPublicSpeedTestRouteImport } from './routes/api/public/speed-test'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScorecardRoute = AuthenticatedScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ProcessIdRoute = ProcessIdRouteImport.update({
  id: '/process/$id',
  path: '/process/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleTokenRoute = ScheduleTokenRouteImport.update({
  id: '/schedule/$token',
  path: '/schedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatesNewRoute =
  AuthenticatedCandidatesNewRouteImport.update({
    id: '/candidates/new',
    path: '/candidates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluationsIndexRoute =
  AuthenticatedEvaluationsIndexRouteImport.update({
    id: '/evaluations/',
    path: '/evaluations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvaluationsApplicationIdRoute =
  AuthenticatedEvaluationsApplicationIdRouteImport.update({
    id: '/evaluations/$applicationId',
    path: '/evaluations/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSpeedTestRoute = ApiPublicSpeedTestRouteImport.update({
  id: '/api/public/speed-test',
  path: '/api/public/speed-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/scorecard': typeof AuthenticatedScorecardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/process/$id': typeof ProcessIdRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/evaluations/$applicationId': typeof AuthenticatedEvaluationsApplicationIdRoute
  '/api/public/speed-test': typeof ApiPublicSpeedTestRoute
  '/evaluations/': typeof AuthenticatedEvaluationsIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/scorecard': typeof AuthenticatedScorecardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/process/$id': typeof ProcessIdRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/evaluations/$applicationId': typeof AuthenticatedEvaluationsApplicationIdRoute
  '/api/public/speed-test': typeof ApiPublicSpeedTestRoute
  '/evaluations': typeof AuthenticatedEvaluationsIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/scorecard': typeof AuthenticatedScorecardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/process/$id': typeof ProcessIdRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/_authenticated/candidates/new': typeof AuthenticatedCandidatesNewRoute
  '/_authenticated/evaluations/$applicationId': typeof AuthenticatedEvaluationsApplicationIdRoute
  '/api/public/speed-test': typeof ApiPublicSpeedTestRoute
  '/_authenticated/evaluations/': typeof AuthenticatedEvaluationsIndexRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/dashboard'
    | '/interviews'
    | '/scorecard'
    | '/settings'
    | '/staff'
    | '/auth/callback'
    | '/process/$id'
    | '/schedule/$token'
    | '/candidates/$id'
    | '/candidates/new'
    | '/evaluations/$applicationId'
    | '/api/public/speed-test'
    | '/evaluations/'
    | '/api/public/cron/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/dashboard'
    | '/interviews'
    | '/scorecard'
    | '/settings'
    | '/staff'
    | '/auth/callback'
    | '/process/$id'
    | '/schedule/$token'
    | '/candidates/$id'
    | '/candidates/new'
    | '/evaluations/$applicationId'
    | '/api/public/speed-test'
    | '/evaluations'
    | '/api/public/cron/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/interviews'
    | '/_authenticated/scorecard'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/auth/callback'
    | '/process/$id'
    | '/schedule/$token'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/candidates/new'
    | '/_authenticated/evaluations/$applicationId'
    | '/api/public/speed-test'
    | '/_authenticated/evaluations/'
    | '/api/public/cron/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProcessIdRoute: typeof ProcessIdRoute
  ScheduleTokenRoute: typeof ScheduleTokenRoute
  ApiPublicSpeedTestRoute: typeof ApiPublicSpeedTestRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scorecard': {
      id: '/_authenticated/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof AuthenticatedScorecardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/process/$id': {
      id: '/process/$id'
      path: '/process/$id'
      fullPath: '/process/$id'
      preLoaderRoute: typeof ProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$token': {
      id: '/schedule/$token'
      path: '/schedule/$token'
      fullPath: '/schedule/$token'
      preLoaderRoute: typeof ScheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates/new': {
      id: '/_authenticated/candidates/new'
      path: '/candidates/new'
      fullPath: '/candidates/new'
      preLoaderRoute: typeof AuthenticatedCandidatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations/': {
      id: '/_authenticated/evaluations/'
      path: '/evaluations'
      fullPath: '/evaluations/'
      preLoaderRoute: typeof AuthenticatedEvaluationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations/$applicationId': {
      id: '/_authenticated/evaluations/$applicationId'
      path: '/evaluations/$applicationId'
      fullPath: '/evaluations/$applicationId'
      preLoaderRoute: typeof AuthenticatedEvaluationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/speed-test': {
      id: '/api/public/speed-test'
      path: '/api/public/speed-test'
      fullPath: '/api/public/speed-test'
      preLoaderRoute: typeof ApiPublicSpeedTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedScorecardRoute: typeof AuthenticatedScorecardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
  AuthenticatedCandidatesNewRoute: typeof AuthenticatedCandidatesNewRoute
  AuthenticatedEvaluationsApplicationIdRoute: typeof AuthenticatedEvaluationsApplicationIdRoute
  AuthenticatedEvaluationsIndexRoute: typeof AuthenticatedEvaluationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedScorecardRoute: AuthenticatedScorecardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  AuthenticatedCandidatesNewRoute: AuthenticatedCandidatesNewRoute,
  AuthenticatedEvaluationsApplicationIdRoute:
    AuthenticatedEvaluationsApplicationIdRoute,
  AuthenticatedEvaluationsIndexRoute: AuthenticatedEvaluationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ProcessIdRoute: ProcessIdRoute,
  ScheduleTokenRoute: ScheduleTokenRoute,
  ApiPublicSpeedTestRoute: ApiPublicSpeedTestRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
