/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as ScheduleTokenRouteImport } from './routes/schedule.$token'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ScheduleTokenRoute = ScheduleTokenRouteImport.update({
  id: '/schedule/$token',
  path: '/schedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/candidates/$id',
    path: '/candidates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/schedule/$token': typeof ScheduleTokenRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/dashboard'
    | '/interviews'
    | '/settings'
    | '/staff'
    | '/schedule/$token'
    | '/candidates/$id'
    | '/api/public/cron/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/dashboard'
    | '/interviews'
    | '/settings'
    | '/staff'
    | '/schedule/$token'
    | '/candidates/$id'
    | '/api/public/cron/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apply'
    | '/auth'
    | '/change-password'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/interviews'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/schedule/$token'
    | '/_authenticated/candidates/$id'
    | '/api/public/cron/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleTokenRoute: typeof ScheduleTokenRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/schedule/$token': {
      id: '/schedule/$token'
      path: '/schedule/$token'
      fullPath: '/schedule/$token'
      preLoaderRoute: typeof ScheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleTokenRoute: ScheduleTokenRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
